### ISSUE TITLE
Missing word

### ISSUE THREAD

**Issue by stvlley** [learn-co-curriculum/phase-3-quiz-ruby-fundamentals#1]
### Canvas Link

https://learning.flatironschool.com/courses/4994/quizzes/27901

### Concern

There is a missing word in one of the answer options for a quiz question!!

The question is question lol: 

"When is it a good idea to use an if statement instead of the ternary operator? Select all that apply."

the answer option with typo:

"When the ternary operator would up more than one line"
>>>>>>>>>>>>>>>>>>>>>^take

**Comment by lizbur10** [comment]
Hi there! Thanks for spotting this issue and providing feedback.

This has now been fixed. Note, however, that if you are working in Canvas the 
changes may not show up there, but they will for future students.

Thanks again for contributing to the Flatiron School curriculum 💙
