### ISSUE TITLE
text for Q8 does not fit on the screen

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/phase-3-quiz-ruby-fundamentals#3]
### Canvas Link

 https://learning.flatironschool.com/courses/5187/quizzes/29528/take/questions/195581

### Concern

In Question 8
The description supplied:
`if letter == "a" || letter == "e" || letter == "i" || letter == "o" || letter == "u"`

is too long to fit on my browser window

Note that Q9 handle a similar case correctly.

### Suggested Changes

Present the material in a way that will fit on the screen. Use the approach taken by Question 9?

**Comment by lizbur10** [comment]
Hi @brigj1. Unfortunately we don't have this level of control with Canvas, but if the code snippet in the question itself (as opposed to the response options) is too wide to see the whole thing, you should be able to scroll to the right.

<img width="590" alt="Screen Shot 2022-07-01 at 9 11 40 AM" src="https://user-images.githubusercontent.com/9666939/176901290-bb09421a-933b-4472-951a-2fb9460ce63b.png">

<img width="585" alt="Screen Shot 2022-07-01 at 9 11 30 AM" src="https://user-images.githubusercontent.com/9666939/176901363-80c1bf32-9940-49f6-bb57-9a06085f5a18.png">

**Comment by brigj1** [comment]
There is no left-right scrolling capability for this question.
<img width="514" alt="Screen Shot 2022-07-01 at 10 06 19 AM" src="https://user-images.githubusercontent.com/10212911/176910709-2eb4a527-6e48-46a0-8980-bffdcd08f0c5.png">
As such, different layout would allow all the text to appear.
